services:
  websocket-server:
    build:
      context: ./websocket-server
    ports:
      - 8000:8000
      
  lobby-server:
    build:
      context: ./lobby-server
    ports:
      - 8001:8000
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - postgres-password
      
  postgres:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - postgres-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  db-data:
  
secrets:
  postgres-password:
    file: lobby-server/postgres-password.txt