services:

  gateway:
    build:
      context: ./gateway
    depends_on:
      service-registry:
        condition: service_started
    
  service-registry:
    build:
      context: ./service-registry
    ports:
      - 50051:50051

  chat:
    build:
      context: ./chat
    environment:
      - HOSTNAME=chat
      - SERVICE_NAME=chat
      - PORT=8008
      - QUART_APP=app:app
      - QUART_BODY_TIMEOUT=5
      - QUART_RESPONSE_TIMEOUT=5
    command: quart run --port 8008 --host 0.0.0.0
    ports:
      - 8008:8008
    depends_on:
      service-registry:
        condition: service_started
    develop:
      watch:
        - action: sync+restart
          path: ./chat
          target: /app
      
  lobby-server:
    build:
      context: ./lobby-server
    ports:
      - 8001:8000
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - postgres-password
    develop:
      watch:
        - action: sync
          path: ./lobby-server
          target: /app
      
  postgres:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - postgres-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  db-data:
  
secrets:
  postgres-password:
    file: lobby-server/postgres-password.txt
