services:

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml

  gateway:
    build:
      context: ./gateway
    ports:
      - 5000:5000
    depends_on:
      service-registry:
        condition: service_started
       
    
  service-registry:
    build:
      context: ./service-registry
    ports:
      - 50051:50051
      - 8080:8080


  chat-1:
    build:
      context: .
      dockerfile: Dockerfile-chat
    secrets:
      - postgres-chat-password
    environment:
      - HOSTNAME=chat-1
      - SERVICE_NAME=chat
      - PORT=8008
      - QUART_APP=app:app
      - QUART_BODY_TIMEOUT=5
      - QUART_RESPONSE_TIMEOUT=5
      - POSTGRES_SERVER=postgres-chat
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chat
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-chat-password
    # command: quart run --port 8008 --host 0.0.0.0
    command: python3 -m hypercorn --keep-alive 3 app:app -b 0.0.0.0:8008 --access-logfile -
    ports:
      - 8008:8008  # http
      - 8090:8090  # prometheus
    depends_on:
      service-registry:
        condition: service_started
      postgres-chat:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./chat
          target: /app
    restart: unless-stopped

  chat-2:
    build:
      context: .
      dockerfile: Dockerfile-chat
    secrets:
      - postgres-chat-password
    environment:
      - HOSTNAME=chat-2
      - SERVICE_NAME=chat
      - PORT=8009
      - QUART_APP=app:app
      - QUART_BODY_TIMEOUT=5
      - QUART_RESPONSE_TIMEOUT=5
      - POSTGRES_SERVER=postgres-chat
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chat
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-chat-password
    # command: quart run --port 8009 --host 0.0.0.0
    command: python3 -m hypercorn --keep-alive 3 app:app -b 0.0.0.0:8009 --access-logfile -
    ports:
      - 8009:8009
    depends_on:
      service-registry:
        condition: service_started
      postgres-chat:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./chat
          target: /app



  postgres-chat:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - postgres-chat-password
    volumes:
      - db-postgres-chat:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-chat-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - 5434:5432


  users-1:
    build:
      context: .
      dockerfile: Dockerfile-users
    ports:
      - 8010:8008
    secrets:
      - postgres-users-password
    environment:
      - HOSTNAME=users-1
      - SERVICE_NAME=users
      - PORT=8009
      - QUART_APP=app:app
      - QUART_BODY_TIMEOUT=5
      - QUART_RESPONSE_TIMEOUT=5
      - POSTGRES_SERVER=postgres-users
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-users-password
    # command: quart --debug run --port 8008 --host 0.0.0.0
    # Task timeout = keep-alive
    command: python3 -m hypercorn --keep-alive 3 app:app -b 0.0.0.0:8008 --access-logfile -
    depends_on:
      # service-registry:
      #   condition: service_started
      postgres-users:
        condition: service_healthy       
    develop:
      watch:
        - action: sync+restart
          path: ./users
          target: /app


  postgres-users:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - postgres-users-password
    volumes:
      - db-postgres-users:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-users-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432

      
volumes:
  db-postgres-users:
  db-postgres-chat:
  
secrets:
  postgres-users-password:
    file: users/postgres-password.txt
  postgres-chat-password:
    file: chat/postgres-password.txt

