# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: registry.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'registry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\x12\x08registry\"4\n\x0bServiceInfo\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x0cServiceQuery\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\"<\n\x10ServiceInstances\x12(\n\tinstances\x18\x01 \x03(\x0b\x32\x15.registry.ServiceInfo2\xa2\x01\n\x0fServiceRegistry\x12\x44\n\x0fRegisterService\x12\x15.registry.ServiceInfo\x1a\x1a.registry.RegisterResponse\x12I\n\x13GetServiceInstances\x12\x16.registry.ServiceQuery\x1a\x1a.registry.ServiceInstancesB\x1bZ\x19service-registry/registryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031service-registry/registry'
  _globals['_SERVICEINFO']._serialized_start=28
  _globals['_SERVICEINFO']._serialized_end=80
  _globals['_REGISTERRESPONSE']._serialized_start=82
  _globals['_REGISTERRESPONSE']._serialized_end=117
  _globals['_SERVICEQUERY']._serialized_start=119
  _globals['_SERVICEQUERY']._serialized_end=155
  _globals['_SERVICEINSTANCES']._serialized_start=157
  _globals['_SERVICEINSTANCES']._serialized_end=217
  _globals['_SERVICEREGISTRY']._serialized_start=220
  _globals['_SERVICEREGISTRY']._serialized_end=382
# @@protoc_insertion_point(module_scope)
